[package]
name = "densmap-analysis"
version = "0.1.0"
authors = ["Petter Johansson <pettjoha@kth.se>"]
edition = "2018"

[dependencies]
byteorder = "1"
regex = "1"
structopt = "0.2"
structopt-derive = "0.2"
walkdir = "2"
